name: Preprocess RAW File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # bisa dijalankan manual

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client -r requirements.txt

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Rohmat-sunaryo.py

      - name: Cek file
        run: |
          print(os.getcwd())
          print(os.listdir("."))
          print(os.listdir("preprocessing"))

      - name: Upload to Google Drive
        env:
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }} # Mengambil kredensial dari GitHub Secrets edited
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }} # Mengambil kredensial dari GitHub Secrets
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          python upload_to_gdrive.py
